name: Bug Report
description: Report an issue to help us improve
labels: [bug]
body:
    - type: textarea
      attributes:
          label: Description
          description: A clear and concise description of what the bug is.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Go to '....'
              2. Click on '....'
              3. Scroll down to '....'
              4. See the error
      validations:
          required: false
    - type: textarea
      attributes:
          label: Expected behavior
          description: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: input
      id: app-version
      attributes:
          label: App Version
          description: Which version of App are you using?
          placeholder: v1.6.0
      validations:
          required: true
    - type: input
      attributes:
          label: Operating System Version
          description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
          placeholder: e.g. Windows 10 21H1, macOS Catalina 10.15.7, or Ubuntu 20.04
      validations:
          required: true
    - type: textarea
      attributes:
          label: Additional Information
          description: |
              A list of assets (e.g. screenshots, error messages) relevant to this bug.

              Tips:
              - You can attach images or log files by clicking this area to highlight it and then dragging files in.
              - **Type `Ctrl+Shift+I` in your keyboard and copy the error message in the `Console` Section**
          placeholder:
              Please make sure to attach the error message(s) returned from Console Log if applicable.
              Note that we won't be able to fix the issue without proper log(s).